# Generated by Django 5.1.6 on 2025-04-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='polarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='subjectivity',
            field=models.FloatField(default=0.0),
        ),
    ]
